# IMPORTANT: Reset this value with a secret only you know.
# python3 -c 'import secrets; print(secrets.token_hex())'
SECRET_KEY="dev"

# Some SAML and SQLAlchemy configuration (don't change)
SAML_PATH="space_trace/saml"
SQLALCHEMY_DATABASE_URI="sqlite:///../instance/trace.db"
SQLALCHEMY_TRACK_MODIFICATIONS=false

# Numbers of seats per row (starting by 1), numbers of rows (starting by 1)
SEAT_NUMBERS=8
SEAT_ROWS=8

# Registration for the event is only possible after the event started.
EVENT_START = "2022-01-17T18:00:00"

# Here are the admins defined of this application. Only these users have the 
# ability to export members in case of a corona case.
# IMPORTANT! this also means the have access to basically all peronal data this
# service stores, so be very carefull whith the persons you allow here!
ADMINS=["flofriday@email.com", "admin@email.com"]

# You can ignore this field for production
# In a development environment this is the email the test user gets. You can
# login as the testuser by visiting /login-debug.
# This is just a workaournd as saml doesn't work with local environments and
# the email is important as the name in the certificate must be matched to 
# your email.
DEBUG_EMAIL="Robert.Nystrom@email.com"